### API calls for BlogPostApp

### Hit the top level route

GET http://localhost:3000 HTTP/1.1


### GET all blogposts

GET http://localhost:3000/api/blogpost HTTP/1.1


### GET a blogpost by ID

GET http://localhost:3000/api/blogpost/48 HTTP/1.1


### GET all users

GET http://localhost:3000/api/user HTTP/1.1


### GET a user by ID

GET http://localhost:3000/api/user/9 HTTP/1.1


### GET all to do items

GET http://localhost:3000/api/todos HTTP/1.1


### GET todos by id

GET http://localhost:3000/api/todos/99 HTTP/1.1